linters:
  enable:
    - errcheck     # проверка ошибок, которые были проигнорированы
    - gosimple     # упрощение кода
    - govet        # стандартный инструмент для анализа кода в Go
    - ineffassign  # проверка неправильных присваиваний
    - staticcheck  # мощный статический анализ
    - typecheck    # проверка типов
    - unused       # обнаружение неиспользуемых функций, переменных и т.д.

run:
  tests: true   # проверка тестов